twist_mux:
  ros__parameters:

    topics:
      nav2:
        topic   : /cmd_vel
        timeout : 0.5
        priority: 10

      joystick:
        topic   : /cmd_vel_joy
        timeout : 0.5
        priority: 20

      emergency_stop:
        topic   : /cmd_vel_stop
        timeout : 1.0
        priority: 100

    output:
      topic: /cmd_vel_out
      stamped: false
